### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ejossev** [equalitie/ipfs-cache#1]
Please attach some...

**Comment by inetic** [comment]
Hi @ejossev. Unfortunately, we haven't decided yet. We have been discussing BSD and MIT so far but we think there is a small possibility that the use of some other software which we're considering will force us to use GPL. Would that be helpful to you?

**Comment by ejossev** [comment]
In all cases, it's gonna be free license we can use in our GPL project?

**Comment by inetic** [comment]
Yes, we have just agreed on [the MIT one](https://github.com/equalitie/ipfs-cache/blob/master/LICENSE).
