### ISSUE TITLE
Store arbitrary data?

### ISSUE THREAD

**Issue by ivilata** [equalitie/ipfs-cache#9]
As of commit 48bbe5c4, ``Injector.insert_content()`` and ``Client.get_content()`` always store and retrieve JSON objects.  However, nothing in the way the library works dictates that we should be ony storing JSON documents.

Maybe we should consider allowing users to just store and retrieve arbitrary data, and have the client do the decoding of whatever it expects?

**Comment by ivilata** [comment]
Added PR #10 with the necessary changes.

**Comment by inetic** [comment]
The two approaches are equivalent. Not only because one can store arbitrary data _inside_ json, but also because one can do this with the `nlohman::json` library:

```
string s1 = "foo";
json j = s1;
string s2 = j;
```

But it's probably cleaner to stick with strings for now.
